### ISSUE TITLE
Can not Sign Up?

### ISSUE THREAD

**Issue by dongbokshin** [aelassas/wexstream#2]
I'm going to create an account for email login.
Email errors continue to occur on the account creation page.
What's the cause?

**Comment by aelassas** [comment]
Did you set up api/.env?

Make sure you set up email settings correctly:

```
WS_SMTP_HOST = host
WS_SMTP_PORT = 587
WS_SMTP_USER = USER
WS_SMTP_PASS = PASSWORD
WS_SMTP_FROM = no-reply@wexstream.com
```

You can use mailjet, sendinblue or any other email platform. You cannot use gmail because Google removed less secure apps setting.

I have just tested the sign up page and it is working fine on my side but you need a working email settings.

**Comment by dongbokshin** [comment]
api/.env
![image](https://user-images.githubusercontent.com/124327198/224659660-3c4b6164-2e7f-4731-8853-bd477e7f9b9a.png)

Sign Up Window
![image](https://user-images.githubusercontent.com/124327198/224659794-c18d85ad-8499-497a-847e-0e1055ffb887.png)

i can't create user
